### ISSUE TITLE
Hey, is this for experienced users? 

### ISSUE THREAD

**Issue by JFMugen** [crazylafo/AE_tl_math#18]
I tried to use it but couldn't say i understand what i should do. (I am not that experienced so that is not a huge surprise)

**Comment by crazylafo** [comment]
hi,
first you must have after Effect CC2015 or higher install on your computer, and to have the base knoledge (composition/layer/effect etc)
-you can download the plugin here for your os https://github.com/crazylafo/AE_tl_math/releases
-once install launch ae and apply the plugin tl math. effect menu->tl->tlmaths)
-to acess to the library, on the effect  click on setup menu and have fun

**Comment by JFMugen** [comment]
Hmm, i didn't know i need to use effect first, i tried to use it from Extensions tab directly :) 

But still, i think i am missing something here? For example, i am using fire_ball preset but all it shows is an image, there is no movement. Is that what it supposed to be?

**Comment by crazylafo** [comment]
When you apply the fire ball's preset there is a checkbox for using time. You can also do some keyframes with other sliders to set the evolution

**Comment by JFMugen** [comment]
Okkkey, i finally understand how it works :D Thanks for the answers.

One last question, like i said i am not experienced and i couldn't be sure when to use it. I mean when they are most useful?

**Comment by crazylafo** [comment]
It depends. Some presets are type of  generators (like fireball/beer/flow..) some you can apply them on solids. Other are type of filters, (like RGB offset, chromawarp) and have to be applied on a footage layer to get result ;).
In the search menu you can use tag search like "generator" and every effects with this tag will be visible.

**Comment by JFMugen** [comment]
Thank you very much for answers and the plugin :)

**Comment by crazylafo** [comment]
you're welcome
