### ISSUE TITLE
Prefix increment issue

### ISSUE THREAD

**Issue by ArashPartow** [crazylafo/AE_tl_math#3]
In the following:

https://github.com/crazylafo/AE_tl_math/blob/a5b121195a716bb577f314d67954fde906104985/src/tl_math_Dialogs.cpp#L200

The search replace may occur on a prefix increment, eg:

`++i --->  +=1i`

**Comment by crazylafo** [comment]
sorry I mixed up with an other issue. you were right. 
unfortunately I had to switch from exprtk to an other way (with GPU). While in multi thread mode,  embedding exprtk in After effect engine is a bit too slow during the renders. (but it was the faster of the tested parser)
