### ISSUE TITLE
Installatatin don't work for me

### ISSUE THREAD

**Issue by bapitsteo** [crazylafo/AE_tl_math#6]
**Don't arrive to install the plugin properly**
Sorry, I think I'm kinda stupid, but I don't achieve to install your plugin properly.
Should I put ALL your downloaded repo like this :

C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore\tl\AE_tl_math-master

Or am I missing something ?
I've been looking for any .aex files I could found but I didn't find any

**Comment by crazylafo** [comment]
The location is good but you copied the source code. AEX file is avaible here in release thread 
https://github.com/crazylafo/AE_tl_math/releases/tag/1.14.1.4

A new version is coming soon with a setup installer more easier. ;).

**Comment by bapitsteo** [comment]
Oh thanks !! now it works ! can't wait the new version !! thanks for the work :)

**Comment by crazylafo** [comment]
you're welcome
